### ISSUE TITLE
爬取视频接口失效？

### ISSUE THREAD

**Issue by Vickzhang** [Amazingxt/douyin#2]
获取分享链接对应的视频信息，函数get_share_video_detail报错：
('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)

**Comment by Amazingxt** [comment]
用 DouYinApi8 class 的接口，cid设置为 e1fbcf46b2a66597，DouYinApi8 里面的函数每天有100次免费调用机会
